// TaskbarDlg.h : header file
//

#include "resource.h"		// main symbols

#include "DemoTaskbarIcon.h"

/////////////////////////////////////////////////////////////////////////////
// CTaskbarDlg dialog

class CTaskbarDlg : public CDialog
{
// Construction
public:
	CTaskbarDlg(CWnd* pParent = NULL);	// standard constructor

// Dialog Data
	//{{AFX_DATA(CTaskbarDlg)
	enum { IDD = IDD_TASKBAR_DIALOG };
	CString	m_sTooltipText;
	BOOL	m_bRouteToMe;
	int		m_nIcon;
	//}}AFX_DATA

	// ClassWizard generated virtual function overrides
	//{{AFX_VIRTUAL(CTaskbarDlg)
	protected:
	virtual void DoDataExchange(CDataExchange* pDX);	// DDX/DDV support
	//}}AFX_VIRTUAL

// Implementation
protected:

	//---------------- Demo Codes: all other codes were generated by AppWizard

	CDemoTaskbarIcon m_TaskbarIcon;

	//---------------- End of this block

	HICON m_hIcon;

	// Generated message map functions
	//{{AFX_MSG(CTaskbarDlg)
	virtual BOOL OnInitDialog();
	afx_msg void OnSysCommand(UINT nID, LPARAM lParam);
	afx_msg void OnPaint();
	afx_msg HCURSOR OnQueryDragIcon();
	afx_msg void OnToggleShow();
	afx_msg void OnIcon1();
	afx_msg void OnIcon2();
	afx_msg void OnSetTooltip();
	afx_msg void OnRouteToMe();
	afx_msg void OnMinimize();
	afx_msg LRESULT OnNotifyTaskbarIcon(WPARAM wParam, LPARAM lParam);
	afx_msg void OnOpen();
	//}}AFX_MSG
	DECLARE_MESSAGE_MAP()
};
