//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Monitor.rc
//
#define MAINMENU                        101
#define ID_TREE_PANE                    101
#define ID_TREE_CONTROL                 102
#define REQOPTIONS                      102
#define ID_DATA_PANE                    103
#define REQLOG                          103
#define ID_LIST_CONTROL                 104
#define IDC_DEVLIST                     1000
#define IDB_ALL                         1001
#define IDB_NONE                        1002
#define IDC_NUMLOG                      1003
#define IDC_REQLOG                      1004
#define IDB_PAUSE                       1005
#define IDB_CLOSE                       1006
#define IDB_RESUME                      1007
#define ID_FILE_EXIT                    40001
#define ID_REQUESTS_OPTIONS             40002
#define ID_REQUESTS_MONITOR             40003
#define ID_REQUESTS_CLEARLOG            40004

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        104
#define _APS_NEXT_COMMAND_VALUE         40005
#define _APS_NEXT_CONTROL_VALUE         1008
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
