//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MSDIDao.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_DATABASE_FORM               101
#define IDD_CATEGORIES                  102
#define IDD_CATEG_PICTURE               102
#define IDR_MAINFRAME                   128
#define IDR_MDIDAOTYPE                  129
#define IDR_CATEGTYPE                   130
#define IDR_CUSTOTYPE                   131
#define IDR_EMPLTYPE                    132
#define IDR_DETAILTYPE                  133
#define IDR_ORDERTYPE                   134
#define IDR_PRODUCTTYPE                 135
#define IDR_SHIPPTYPE                   136
#define IDR_SUPPLTYPE                   137
#define IDS_ERROR_OPEN_TABLE            138
#define IDS_PRN_USER_NAME               139
#define IDS_PRN_APPLICATION_NAME        140
#define IDS_PRN_PAGE_FORMAT             141
#define IDS_PRN_DATE_FORMAT             142
#define IDR_DIBTYPE                     143
#define IDC_DATABASE_NAME               1000
#define IDC_DATABASE_VERSION            1001
#define IDC_CATEG_ID                    1002
#define IDC_CATEG_PICTURE               1003
#define IDC_CATEG_NAME                  1004
#define IDC_CATEG_DESCRIPTION           1005
#define ID_TABLE_CATEG                  32772
#define ID_TABLE_CUSTOM                 32773
#define ID_TABLE_EMPL                   32774
#define ID_TABLE_DETAIL                 32775
#define ID_TABLE_ORDER                  32776
#define ID_TABLE_PRODUCT                32777
#define ID_TABLE_SHIPP                  32778
#define ID_TABLE_SUPPL                  32779
#define ID_FORM_CATEG                   32780
#define ID_VIEW_DIB                     32781

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        103
#define _APS_NEXT_COMMAND_VALUE         32782
#define _APS_NEXT_CONTROL_VALUE         1006
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
