#pragma once

using namespace ATL;

template <class T>
class CProxy_IProjectTreeCtrlEvents : public IConnectionPointImpl<T, &__uuidof(_IProjectTreeCtrlEvents), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
