//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by dtset.rc
//
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_DATENTRY_DIALOG             102
#define IDD_DTSET                       102
#define IDS_EG                          102
#define IDR_MAINFRAME                   128
#define IDC_CDATE                       1000
#define IDC_CLTIMEOFDAY                 1001
#define IDC_CLTIMESPAN                  1002
#define IDC_CLDATE                      1003
#define IDC_CREDITS                     1072
#define IDC_GREGORIAN_DATE              1074
#define IDC_JULIAN_DATE                 1075
#define IDC_CDATE_FORMAT                1076
#define IDC_CLTIMESPAN_FORMAT           1077
#define IDC_CLTIMEOFDAY_FORMAT          1078
#define IDC_CLDATE_FORMAT               1079
#define IDC_CDATE_EG                    1080
#define IDC_CLTIMESPAN_EG               1081
#define IDC_CLTIMEOFDAY_EG              1082
#define IDC_CLDATE_EG                   1083
#define IDC_BEGINDAYOFWEEK              1084

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1085
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
