//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by plotresources.rc
//
#define IDD_XY_SETTINGS                 4001
#define IDD_XYSETTINGS_TITLE            4002
#define IDD_XYSETTINGS_SUBTITLE         4003
#define IDD_XYSETTINGS_PLOTRANGES       4004
#define IDD_XYSETTINGS_MAJORGRIDS       4005
#define IDD_XYSETTINGS_MINORGRIDS       4006
#define IDD_XYSETTINGS_BACKGROUND       4007
#define IDD_XYSETTINGS_AUTOSETTINGS     4008
#define IDD_XYSETTINGS_LEGEND           4009
#define IDD_AXIS_SETTINGS               4010
#define IDD_DATA_SETTINGS               4011
#define IDD_XYSETTINGS_SELZONE          4012
#define IDD_XYSETTINGS_CURSORS          4013
#define IDD_AXISSETTINGS_TITLE          4014
#define IDD_AXISSETTINGS_TICKLABEL      4015
#define IDD_AXISSETTINGS_RANGE          4016
#define IDD_AXISSETTINGS_MAJORTICKS     4017
#define IDD_AXISSETTINGS_MINORTICKS     4018
#define IDD_AXISSETTINGS_AXISCOLOR      4019
#define IDD_AXISSETTINGS                4020
#define IDD_DATASETTINGS_TITLE          4021
#define IDD_DATASETTINGS_LINE           4022
#define IDD_DATASETTINGS_CHARTTYPE      4023
#define IDD_DATASETTINGS_MAKERS         4024
#define IDD_DATASETTINGS_FILLENCLOSED   4025
#define IDD_DATASETTINGS_MANAGEMENT     4026
#define IDD_DATASETTINGS                4027
#define IDD_XYSETTINGS_COPYRIGHT        4028
#define IDC_AS_TITLE_FONT               4100
#define IDC_AS_COLOR_LABEL_FONT         4101
#define IDC_DS_COLOR_AUTO               4102
#define IDC_DS_LINESTYLE_AUTO           4103
#define IDC_DS_LINESTYLE                4104
#define IDC_DS_CHART_TYPE               4105
#define IDC_DS_LINE_SIZE                4106
#define IDC_DS_ENCLOSEDCURVE_FILL       4107
#define IDC_DS_MARKER_SHAPE             4108
#define IDC_DS_MARKER_SIZE              4109
#define IDC_DS_MARKER_FILL              4110
#define IDC_PS_XRANGE_LOW               4111
#define IDC_PS_XRANGE_HIGH              4112
#define IDC_PS_YRANGE_LOW               4113
#define IDC_PS_YRANGE_HIGH              4114
#define IDC_PS_AUTO_XRANGE              4115
#define IDC_PS_AUTO_YRANGE              4116
#define IDC_PS_MAJOR_HORIZONTAL_GRIDS   4117
#define IDC_PS_MINOR_HORIZONTAL_GRIDS   4118
#define IDC_PS_MAJOR_VERTICAL_GRIDS     4119
#define IDC_PS_MINOR_VERTICAL_GRIDS     4120
#define IDC_PS_COLOR_MAJOR_GRIDS        4121
#define IDC_PS_COLOR_MINOR_GRIDS        4122
#define IDC_PS_COLOR_TITLE_FONT         4123
#define IDC_PS_COLOR_SUBTITLE_FONT      4124
#define IDC_PS_PLOT_TITLE               4125
#define IDC_PS_PLOT_SUBTITLE            4126
#define IDC_PS_TITLE_FONT               4127
#define IDC_PS_SUBTITLE_FONT            4128
#define IDC_AS_LABEL_FONT               4129
#define IDC_PS_CHOOSE_TITLE_FONT        4130
#define IDC_PS_CHOOSE_SUBTITLE_FONT     4131
#define IDC_PS_COLOR_BACKGROUND         4132
#define IDC_AXIS_PREVIOUS               4133
#define IDC_PS_COLOR_BORDER             4134
#define IDC_AXIS_NEXT                   4135
#define IDC_PS_BKGND_COLOR1             4136
#define IDC_AS_LABEL                    4137
#define IDC_PS_BKGND_COLOR2             4138
#define IDC_PS_COLOR_DATAAREA           4139
#define IDC_AS_NUMBER_MAJOR_TICKS       4140
#define IDC_AS_NUMBER_MINOR_TICKS       4141
#define IDC_AS_AUTO_MAJOR_TICKS         4142
#define IDC_PS_LEGEND_FONT              4143
#define IDC_AS_AUTO_MINOR_TICKS         4144
#define IDC_PS_CHOOSE_LEGEND_FONT       4145
#define IDC_AS_AUTO_XRANGE              4146
#define IDC_AS_XRANGE_HIGH              4147
#define IDC_AS_XRANGE_LOW               4148
#define IDC_AS_PLOT_TITLE               4149
#define IDC_AS_CHOOSE_TITLE_FONT        4150
#define IDC_AS_COLOR_TITLE_FONT         4151
#define IDC_AS_MAJOR_TICK_LENGTH        4152
#define IDC_AS_MINOR_TICK_LENGTH        4153
#define IDC_DS_DATA_TITLE               4154
#define IDC_AS_MAJOR_TICK_SIZE          4155
#define IDC_AS_CHOOSE_LABEL_FONT        4156
#define IDC_DS_COLOR_LINE               4157
#define IDC_AS_MINOR_TICK_SIZE          4158
#define IDC_AS_COLOR_MAJORTICK          4159
#define IDC_DS_COLOR_ENCLOSEDCURVE      4160
#define IDC_AS_COLOR_MINORTICK          4161
#define IDC_AS_COLOR_AXIS               4162
#define IDC_DS_MARKER_FREQ_EVERY        4163
#define IDC_DS_MARKER_FREQ_NTH          4164
#define IDC_DS_MARKER_FREQ_NUMBER       4165
#define IDC_DS_MARKER_FREQ_TOTAL        4166
#define IDC_DS_MARKER_FREQ_TOTAL_DATA   4167
#define IDC_DS_MARKER_FREQ_NONE         4168
#define IDC_DATA_NEXT                   4169
#define IDC_DATA_PREVIOUS               4170
#define IDC_DATASET_LABEL               4171
#define IDC_PLOT_TO_SIZE                4172
#define IDC_MAINTAIN_ASPECT_RATIO       4173
#define IDC_PS_MAJOR_GRID_SIZE          4174
#define IDC_PS_BORDER_SIZE              4175
#define IDC_PS_MINOR_GRID_SIZE          4176
#define IDC_PS_PLOT_SUBTITLESHOW        4177
#define IDS_COLOR_TABLES                4178
#define IDS_COLOR_TABLE_ID              4179
#define IDC_PS_DATA_COLOR_AUTO          4180
#define IDC_PS_DATA_LINESTYLE_AUTO      4181
#define IDC_PS_MAJOR_LINESTYLE          4182
#define IDC_PS_MINOR_LINESTYLE          4183
#define IDC_DATA_SAVE                   4184
#define IDC_DS_NUMOFPOINTS              4185
#define IDC_PS_BACKGROUND_GRADIENT      4186
#define IDC_PS_PLOT_LEGEND              4187
#define IDC_PS_PLOT_LEGENDTRANSPARENT   4188
#define IDC_PS_BACKGROUND_GRADIENTHORV  4189
#define IDC_DATA_LOAD                   4190
#define IDC_AS_MAJORTICK_POSITION       4191
#define IDC_AS_MINORTICK_POSITION       4192
#define IDC_AS_COLOR_SAMECHECK          4193
#define IDC_PS_ZONE_XSELECT             4194
#define IDC_PS_XZONE_START              4195
#define IDC_PS_XZONE_END                4196
#define IDC_PS_CURSOR_XUSE              4197
#define IDC_PS_ZONE_YSELECT             4198
#define IDC_PS_CURSER_XPOS              4199
#define IDC_PS_YZONE_START              4200
#define IDC_PS_CURSOR_YUSE              4201
#define IDC_PS_YZONE_END                4202
#define IDC_PS_CURSER_YPOS              4203
#define IDC_PS_CURSOR_BOND              4204
#define IDC_PS_CURSOR_CURVEBOND         4205
#define IDC_PS_COLOR_SELZONE            4206
#define IDC_PS_COLOR_CURSOR             4207
#define IDC_AXIS_SETTINGS_TAB           4208
#define IDC_DATA_SETTINGS_TAB           4209
#define IDC_AS_LABEL_SHOW               4210
#define IDC_AS_AXIS_SIZE                4211
#define IDC_AS_AXIS_STYLE               4212
#define IDC_DS_LISTDATASETS             4213
#define IDC_AS_LISTAXES                 4214
#define IDC_AS_SAVE_WHEN_SWITCHING      4215
#define IDC_DS_SAVE_WHEN_SWITCHING      4216
#define IDC_PS_VERSION                  4217
#define IDC_PS_AUTHOR                   4218

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        6000
#define _APS_NEXT_COMMAND_VALUE         33000
#define _APS_NEXT_CONTROL_VALUE         4220
#define _APS_NEXT_SYMED_VALUE           500
#endif
#endif
