///////////////////////////////////////////////////////////
//
// Event_I.idl - Interface description ITangramModelEvent 
//

///////////////////////////////////////////////////////////
//
// Imports
//
import "unknwn.idl" ; 

/////////////////////////////////////////////////////////////
// ITangramModelEvent
//
[
	object,
	uuid(b53313c5-20c4-11d0-9c6c-00a0c90a632c),
	helpstring("ITangramModelEvent Interface"),
	pointer_default(unique)
]
interface ITangramModelEvent: IUnknown
{
	HRESULT OnModelChange() ;
};

