/////////////////////////////////////////////////////////////////////
// Class Creator Version 2.0.000 Copyrigth (C) Poul A. Costinsky 1994
///////////////////////////////////////////////////////////////////
// Implementation File TypedLocalHeap.cpp
// class CWizTypedLocalHeap
//
// 07/04/1996 21:22                             Author: Poul
///////////////////////////////////////////////////////////////////


#include "stdafx.h"

#include "TypedLocalHeap.h"


#ifdef _DEBUG
#undef THIS_FILE
static char BASED_CODE THIS_FILE[] = __FILE__;
#endif

///////////////////////////////////////////////////////////////////
// class CWizTypedLocalHeap

#define new DEBUG_NEW
//*****************************************************************
//*****************************************************************
