#pragma once

using namespace ATL;

template <class T>
class CProxy_ISceneCtrlEvents : public IConnectionPointImpl<T, &__uuidof(_ISceneCtrlEvents), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
