import "C:\Program Files\Microsoft SDKs\Windows\v7.0A\include\prsht.idl";
import "C:\Program Files\Microsoft SDKs\Windows\v7.0A\include\mshtml.idl";
import "c:\program files\microsoft sdks\windows\v7.0a\include\dimm.idl";
import "c:\program files\microsoft sdks\windows\v7.0a\include\dispex.idl";
import "C:\Program Files\Microsoft SDKs\Windows\v7.0A\include\mshtmhst.idl";
import "c:\program files\microsoft sdks\windows\v7.0a\include\docobj.idl";
import "C:\Program Files\Microsoft SDKs\Windows\v7.0A\include\exdisp.idl";
import "C:\Program Files\Microsoft SDKs\Windows\v7.0A\include\objsafe.idl";

[
	object,
	uuid(296E91A9-7F72-49FA-88F7-7B3AFEE9422D),
	oleautomation,
	helpstring("ICalc Interface"),
	pointer_default(unique)
] 
#line 14 "d:\\vc++\\atl internals 2e src\\chapter 02\\ccomgitptr\\gittest\\calc.h"
interface ICalc : IUnknown {
#line 16 "d:\\vc++\\atl internals 2e src\\chapter 02\\ccomgitptr\\gittest\\calc.h"
	[id(1),helpstring("method Add")] HRESULT  Add([in] DOUBLE Op1, [in] DOUBLE Op2, [out,retval] DOUBLE *Result);
};


[ version(1.0), uuid(27929090-3FC0-4BB4-8C81-6FD510EA27E6), helpstring("GITTest 1.0 Type Library") ]
library GITTest
{
	importlib("stdole2.tlb");
	importlib("olepro32.dll");

	[
		version(1.0),
		uuid(10AFDDFC-CBD6-4072-9065-D89D88028444),
		helpstring("Calc Class")
	] 
#line 32 "d:\\vc++\\atl internals 2e src\\chapter 02\\ccomgitptr\\gittest\\calc.h"
	coclass CCalc {
		interface ICalc;
	};

}

