/*
Module : DTIMERES.H
Purpose: Defines the help ids for all messages the DTime Dll generates
Created: PJN / DATE/1 / 26-03-1996
History: None

Copyright (c) 1996 by PJ Naughter.  
All rights reserved.

*/


#ifndef __DTIMERES_H__
#define __DTIMERES_H__



/////////////////////////////////////////////////////////////////////////////
// Standard string error/warnings

#define DT_IDS_INVALID_DATE_RANGE      16041
#define DT_IDS_INVALID_DATE_MIN        16044
#define DT_IDS_INVALID_DATE_MAX        16047
#define DT_IDS_INVALID_TIMESPAN_RANGE  16042
#define DT_IDS_INVALID_TIMESPAN_MIN    16045
#define DT_IDS_INVALID_TIMESPAN_MAX    16048
#define DT_IDS_INVALID_TIMESPAN        16058
#define DT_IDS_INVALID_TIMEOFDAY_RANGE 16043
#define DT_IDS_INVALID_TIMEOFDAY_MIN   16046
#define DT_IDS_INVALID_TIMEOFDAY_MAX   16049
#define DT_IDS_INVALID_LDATE_MIN       16061
#define DT_IDS_INVALID_LDATE_MAX       16062


#endif //__DTIMERES_H__