//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Panel3d.rc
//
#define IDS_PANEL3D                     1
#define IDD_ABOUTBOX_PANEL3D            1
#define IDB_PANEL3D                     1
#define IDI_ABOUTDLL                    1
#define IDS_PANEL3D_PPG                 2
#define IDS_PANEL3D_PPG_CAPTION         100
#define IDD_PROPPAGE_PANEL3D            100
#define IDC_RADIO_INSET                 201
#define IDC_RADIO_RAISED                202
#define IDC_EDIT_CAPTION                203
#define IDC_EDIT_BEVELWIDTH             204
#define IDC_COMBO1                      205
#define IDC_CBTEXTALIGN                 205
#define IDC_CHK3D                       206
#define IDC_CHKDRAWBORDER               207
#define IDC_RADIOINSET                  208
#define IDC_RADIORAISED                 209
#define IDC_RADIONONE                   210

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        202
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         210
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
