//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Wizard1.rc
//
#define TITLE_SIZE                      24
#define IDD_ABOUTBOX                    103
#define IDD_INTRO                       106
#define IDD_PAGE1                       107
#define IDD_PAGE2                       108
#define IDD_PAGE3                       109
#define IDD_PAGE4                       110
#define IDB_DONE                        111
#define IDB_INTRO                       112
#define IDB_SERVER                      113
#define IDB_QUESTION                    114
#define IDB_FOOD                        115
#define IDB_WIZARD                      116
#define IDR_MAINFRAME                   128
#define IDC_COMPANY                     2001
#define IDC_EMAIL                       2004
#define IDC_INTRO1                      2005
#define IDC_INTRO2                      2006
#define IDC_INTROBITMAP                 2007
#define IDC_FIRSTNAME                   2008
#define IDC_PAGE2_1                     2009
#define IDC_PAGE2_2                     2010
#define IDC_PAGE2_3                     2011
#define IDC_PAGE2_4                     2012
#define IDC_PAGE2_TEXT                  2013
#define IDC_PAGE3_1                     2014
#define IDC_PAGE3_2                     2015
#define IDC_PAGE3_3                     2016
#define IDC_PAGE3_4                     2017
#define IDC_PAGE3_TEXT                  2018
#define IDC_LASTNAME                    2020
#define IDC_TITLE                       2021
#define IDC_PAGE4_TEXT                  2022
#define ID_FILE_EXIT                    32775
#define ID_FILE_RUNWIZARD               40009
#define ID_HELP_ABOUT                   40010
#define ID_INDICATOR_CAPS               0xE701
#define ID_INDICATOR_NUM                0xE702
#define ID_INDICATOR_SCRL               0xE703
#define IDS_INTRO1                      59141
#define IDS_INTRO2                      59142
#define IDS_PAGE1_TITLE                 59143
#define IDS_PAGE2_1                     59144
#define IDS_PAGE2_2                     59145
#define IDS_PAGE2_3                     59146
#define IDS_PAGE2_4                     59147
#define IDS_PAGE2_TEXT                  59148
#define IDS_PAGE2_TITLE                 59149
#define IDS_PAGE3_1                     59150
#define IDS_PAGE3_2                     59151
#define IDS_PAGE3_3                     59152
#define IDS_PAGE3_4                     59153
#define IDS_PAGE3_TEXT                  59154
#define IDS_PAGE3_TITLE                 59155
#define IDS_WELCOME                     59156
#define IDS_PAGE4_TITLE                 59157
#define IDS_PAGE4_TEXT                  59158

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        117
#define _APS_NEXT_COMMAND_VALUE         40011
#define _APS_NEXT_CONTROL_VALUE         2023
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
