//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by SAMCLS16.RC
//
#define IDD_SAMPAGE                     101
#define IDI_SAMICON                     102
#define IDC_SAMNAME                     1000
#define IDB_MOREINFO                    1001
#define IDC_INFOLABEL                   1002
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        103
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
