///////////////////////////////////////////////////////////////////
// Used by MENU1.RC and MENU1.CPP

// Resources
#define IDR_MAINFRAME     128
#define IDR_CONTEXTMENU   129
#define IDR_ACCELERATOR1  130

//
// Resource items
//

// Shared IDs for menu / status bar string table items
#define ID_HELPABOUT      32771
#define ID_FILESAVEAS     32772
#define ID_FILEOPEN       32773
#define ID_FILESAVE       32774
#define ID_FILEEXIT       32775

// Context menu item IDs
#define ID_CONTEXTMENU1   32776
#define ID_CONTEXTMENU2   32777

// String table IDs for AfxMessageBox messages
#define IDS_FILEOPEN      32779
#define IDS_FILESAVE      32780
#define IDS_FILESAVEAS    32781
#define IDS_HELPABOUT     32782
#define IDS_CONTEXT1      32783
#define IDS_CONTEXT2      32784

// Shared ID for custom accelerator message and accelerator item
#define ID_MESSAGE1       32785 
