//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by DATENT16.RC
//
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_DATENTRY_DIALOG             102
#define IDR_MAINFRAME                   128
#define IDC_CDATE                       1000
#define IDC_CLTIMEOFDAY                 1001
#define IDC_CLTIMESPAN                  1002
#define IDC_CLDATE                      1003
#define IDC_CREDITS                     1072

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1074
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
