/* Generated by Together */

#include "stdafx.h"
#include "EProperty.h"
#include "EPropList.h"
#include "EGridView.h"


#ifdef _DEBUG
#define new DEBUG_NEW
#undef THIS_FILE
static char THIS_FILE[] = __FILE__;
#endif


IMPLEMENT_DYNCREATE(EGridView, CView)

BEGIN_MESSAGE_MAP(EGridView, CView)
	//{{AFX_MSG_MAP(CPropListView)
	ON_WM_CREATE()
	ON_WM_SIZE()
	ON_WM_ERASEBKGND()
	//}}AFX_MSG_MAP
END_MESSAGE_MAP()

EGridView::EGridView()
{
}

EGridView::~EGridView()
{
}

void EGridView::OnDraw(CDC* pDC)
{
}

int EGridView::OnCreate(LPCREATESTRUCT lpCreateStruct) 
{
	
	if (CView::OnCreate(lpCreateStruct) == -1)
		return -1;
	
	CRect rect;
	GetClientRect(&rect);

	m_GridCtrl.Create( NULL , "Grid Property Control" , WS_VISIBLE | WS_CHILD , rect , this , -1 );

//	ModifyStyleEx( WS_EX_CLIENTEDGE , 0 );

	return 0;
}


BOOL EGridView::OnEraseBkgnd(CDC* pDC) 
{
	return FALSE;
}

void EGridView::OnSize(UINT nType, int cx, int cy) 
{
	CView::OnSize(nType, cx, cy);
	CRect rect;
	GetClientRect(&rect);
	m_GridCtrl.MoveWindow(rect);
}

/*
void EGridView::OnInitialUpdate()
{
	SetGridModel( NULL );
}
*/

/*
void EGridView::SetGridModel( IGridModel* pModel )
{
	m_GridCtrl.SetGridModel( pModel );
}
*/