/* Generated by Together */

#ifndef EPROPERTYCHECK_H
#define EPROPERTYCHECK_H

#include "EProperty.h"
#include "EIconTextButtonProperty.h"

class EPropertyCheck : public EIconTextButtonProperty
{

public:	

    EPropertyCheck( IPropertyHost* pHost , const CString& sName , bool* pProperty );
	virtual EPropertyCheck::~EPropertyCheck();

	virtual bool OnSpaceKey();							//return true if property changed

	virtual bool OnLButtonDown( EPropWnd* pParent , CPoint p );

	virtual int GetHeight( CDC* pDC );
	virtual void DrawIcon( CDC* pDC , EPropWnd* pParent , const CRect& Rect );

	virtual int GetIconWidth();

	virtual CString GetTextValue();
	

protected:

	bool ToggleCheck();

};
#endif //EPROPERTYCHECK_H