/* Generated by Together */

#ifndef EPROPERTYFLOAT_H
#define EPROPERTYFLOAT_H

#include "ENumericProperty.h"

class EPropertyFloat : public ENumericProperty
{

public:

    EPropertyFloat( IPropertyHost* pHost , const CString& sName , float* pProperty , const CString& sUnit , float fMinAllowed=0 , float fMaxAllowed=0 , bool bEnabled=true );
	virtual ~EPropertyFloat();

	//
	// ENumericProperty
	//

	virtual double GetNumericValue();
	virtual bool SetNumeric( double dVarValue );
	virtual int GetNumSignificantDigits();
};


#endif