//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by BTNCOLOR.RC
//
#define IDR_MAINFRAME                   2
#define IDR_BTNCOLTYPE                  3
#define IDS_STRINGCHART                 4
#define IDD_ABOUTBOX                    100
#define IDB_CHART                       102

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        103
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
