//////////////////////////////////////////////////////////
// WINDOWS++ CLASS LIBRARY.  Copyright 1992,1996 Paul DiLascia.
// FILE: WPID.H
//

#ifndef WPPID_H
#define WPPID_H

////////////////
// Menu IDs
// 
#define WPIDM_EXIT		10
#define WPIDM_NEW			11
#define WPIDM_OPEN		12
#define WPIDM_SAVE		13
#define WPIDM_SAVEAS		14
#define WPIDM_PRINT		15
#define WPIDM_ABOUT		16

#define WPIDM_CUT			17
#define WPIDM_COPY		18
#define WPIDM_PASTE		19

#define WPID_APP				100

#endif
