// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "chartctrl1.h"

/////////////////////////////////////////////////////////////////////////////
// CChartctrl1

IMPLEMENT_DYNCREATE(CChartctrl1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CChartctrl1 properties

/////////////////////////////////////////////////////////////////////////////
// CChartctrl1 operations
