//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by DynLink3.rc
//
#define IDS_TEXT1                       1
#define IDD_DIALOG1                     129
#define IDC_TEXT1                       1000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
