//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by MSDI.RC
//
#define IDR_MSDITYPE                    2
#define IDR_GRAFTYPE                    3
#define IDR_OUTTYPE                     4
#define IDR_MAINFRAME                   5
#define IDD_ABOUTBOX                    100
#define IDD_MSDI_FORM                   101
#define ID_VIEW_VIEW2                   32771
#define ID_OUTPUT_TEXT                  32772
#define ID_OUTPUT_ERASE                 32773
#define ID_VIEW_OUTPUT                  32774

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         32775
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
