///////////////////////////////////////////////////////////
// Resource IDs for HELP1

#define IDM_ABOUTBOX            0x0010  // system menu
#define IDD_ABOUTBOX            100     // dialog box
#define IDS_ABOUTBOX            101     // string table
#define IDD_HELP1_DIALOG        102     // dialog box
                                       
#define IDR_MAINFRAME           128     // icon
#define IDB_BITMAP1             129     // bitmap
#define IDC_BTNHELP             130     // push-button
                                       
#define IDC_EDIT1               1000   
#define IDC_EDIT2               1001
#define IDC_CHECK1              1002
#define IDC_CHECK2              1003
#define IDC_CHECK3              1004

///////////////////////////////////////////////////////////
// Control Help Context IDs

#define HIDCANCEL               10
#define HID_HELP                20
#define HIDC_EDIT1              30
#define HIDC_EDIT2              40
#define HIDC_CHECK1             50
#define HIDC_CHECK2             60
#define HIDC_CHECK3             70
#define HIDD_HELP1_DIALOG       80
