///////////////////////////////////////////////////////////////////
// Used by DIALOG1.RC and DIALOG1.CPP

// Resources
#define IDR_MAINFRAME     128

//
// Resource items
//

// Shared IDs for menu / status bar string table items
#define ID_FILE_EXIT           32775
#define ID_FILE_CHOOSECOLOR    40001
#define ID_FILE_FONT           40002
#define ID_FILE_FIND           40003
#define ID_FILE_REPLACE        40004
#define ID_FILE_PAGESETUP      40005
#define ID_FILE_PRINTSETUP     40006
#define ID_FILE_SAVEAS         40007
#define ID_HELP_ABOUT          40008
#define IDS_HELP_ABOUT         40009

