// stdafx.h : include file for standard system include files,
//  or project specific include files that are used frequently, but
//      are changed infrequently
//
// Docktest demo of Dockable Views functionality

#include <afxwin.h>         // MFC core and standard components
#include <afxext.h>         // MFC extensions
#include <afxcmn.h>			// MFC Win'95 common control
#include <afxole.h>			// MFC OLE extensions

// some extended styles that come in handy occasionally.
#ifndef WS_EX_CONTEXTHELP
#define WS_EX_CONTEXTHELP       0x0400L
#endif

#ifndef WS_EX_CLIENTEDGE
#define WS_EX_CLIENTEDGE 0x0200L
#endif

#include "OXAdvancedAssert.h"