///////////////////////////////////////////////////////////////////
// Module  : MAINFRM.CPP
//
// Purpose : Implementation of the CMainFrame class.
//
// Author  : Rob McGregor - rob_mcgregor@compuserve.com
//
// Date    : 05-12-96
///////////////////////////////////////////////////////////////////

#include "stdafx.h"     // Standard Include
#include "DocView1.h"   // Application
#include "MainFrm.h"    // Frame Window

IMPLEMENT_DYNCREATE(CMainFrame, CFrameWnd)

///////////////////////////////////////////////////////////////////
// CMainFrame construction/destruction

CMainFrame::CMainFrame()
{
}

CMainFrame::~CMainFrame()
{
}

