///////////////////////////////////////////////////////////////////
// Header  : MAINFRM.CPP
//
// Purpose : Implementation of the CMainFrame class.
//
// Author  : Rob McGregor - rob_mcgregor@compuserve.com
//
// Date    : 05-12-96
///////////////////////////////////////////////////////////////////

#include "stdafx.h"     // Standard include
#include "DocView2.h"   // Application
#include "MainFrm.h"    // Frame Window

IMPLEMENT_DYNCREATE(CMainFrame, CFrameWnd)

// Message Map for CMainFrame
BEGIN_MESSAGE_MAP(CMainFrame, CFrameWnd)

END_MESSAGE_MAP()

///////////////////////////////////////////////////////////////////
// CMainFrame construction/destruction

CMainFrame::CMainFrame()
{
}

CMainFrame::~CMainFrame()
{
}

