//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Jiggler.rc
//
#define IDS_JIGGLER                     1
#define IDD_ABOUTBOX_JIGGLER            1
#define IDB_JIGGLER                     1
#define IDI_ABOUTDLL                    1
#define IDS_JIGGLER_PPG                 2
#define IDS_JIGGLER_PPG_CAPTION         100
#define IDD_PROPPAGE_JIGGLER            100
#define IDC_EDIT_CAPTION                201
#define IDC_EDIT_INTERVAL               202
#define IDC_RADIO_WHITE                 203
#define IDC_RADIO_GRAY                  204
#define IDC_EDIT_FONTSIZE               205

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        201
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         204
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
