///////////////////////////////////////////////////////////////////
// Standard include file for precompiled headers in MSVC++

#include <afxwin.h>  // MFC core and standard components
#include <afxext.h>  // MFC extension classes
#include <afxcmn.h>  // MFC common controls
#include <afxres.h>  // MFC resources
#include <afxdlgs.h> // MFC dialogs
#include <afxmt.h>   // MFC multithreading

///////////////////////////////////////////////////////////////////
