//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Main.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDI_COMP2COMP                   16
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_HOOKAPI_DLG                 101
#define IDD_MAIN_DIALOG                 102
#define IDS_APP_NAME                    102
#define IDD_ENUMDIALOG                  103
#define IDR_MAINFRAME                   128
#define IDR_REMOTECONTROL               128
#define IDD_START_SERVICE_DLG           129
#define IDB_LOG                         129
#define IDR_MENU1                       130
#define IDD_ADDRULEDLG                  130
#define IDI_IPHeader                    130
#define IDI_TCPHEADER                   131
#define IDD_GROUP_TALK_DLG              132
#define IDI_ICONTO                      132
#define IDD_IOCOMPLETEPORT_TALK_DLG     133
#define IDD_ComFile_DIALOG              134
#define IDD_NETSTAT_DLG                 135
#define IDR_MENU2                       136
#define IDD_NET_STATISTICS_DLG          137
#define IDR_MENU3                       138
#define IDD_IPHLP_MISC                  139
#define IDD_LSP_DLG                     141
#define IDR_MENU4                       141
#define IDD_IPHLP_MISC3                 142
#define IDR_MENU5                       142
#define IDD_HOOK_FIREWALL_DLG           143
#define IDR_MENU6                       144
#define IDD_P2P_UDP_SERVER_DLG          144
#define IDD_P2P_UDP_CLIENT_DLG          145
#define IDR_SYS_TRAY_CONTEXT            145
#define IDD_SNIFFER_DLG                 146
#define IDD_PING_DLG                    147
#define IDI_ICON                        148
#define IDD_TRACEROUTE_DLG              149
#define IDD_NET_WAKE_MACHINE_DLG        150
#define IDD_REMOTEADMIN_DLG             151
#define IDD_TIME_SETTINGS               153
#define IDI_MACHINE_ON_NETWORK          154
#define IDI_MACHINE                     155
#define IDD_REMOTE_LOGON                156
#define IDR_MENU_MACHINE                157
#define IDD_PROGRESS_DLG                160
#define IDD_EXECUTE_PROCESS             161
#define IDR_MENU_END_PROCESS            162
#define IDR_REMOTEADMIN                 163
#define IDD_IPHOOKDRV_VIEW              164
#define IDD_IPHOOKDRV_DLG               165
#define IDR_IPHOOKDRV                   166
#define IDD_HIDE_PROCESS_DLG            167
#define IDR_MENU_HIDE_PROCESS           168
#define IDD_HIDEPROCESS_DETAIL_DLG      169
#define IDC_LIST_FUNCTION               1000
#define IDC_RECORD                      1000
#define IDC_BUTTONOPEN                  1000
#define IDC_LIST_DATA                   1000
#define IDC_LOGON                       1000
#define IDC_EDIT_PROCESS_NAME           1000
#define IDC_LISTRULES                   1000
#define IDC_STATIC_PLACE                1001
#define IDC_CLEAR                       1001
#define IDC_BUTTONCLOSE                 1001
#define IDC_EDIT_SPECIFICDATA           1001
#define IDC_SOURCE_IP                   1001
#define IDC_PASSWORD                    1001
#define IDC_EDIT_USER                   1001
#define IDC_COMBOPORT                   1002
#define IDC_BTN_TARGET                  1002
#define IDC_SOURCE_PORT                 1002
#define IDC_REMOTEIP                    1002
#define IDC_EDIT_PASSWORD               1002
#define IDC_SELGROUP                    1003
#define IDC_EDITFILE                    1003
#define IDC_BTN_PAUSE                   1003
#define IDC_SOURCE_MASK                 1003
#define IDC_SELUSER                     1004
#define IDC_BUTTONBROWSER               1004
#define IDC_BTN_CLOSE                   1004
#define IDC_DEST_IP                     1004
#define IDC_EDIT_DOMAIN                 1004
#define IDC_BTN_SERVICE_MENU            1005
#define IDC_USERS                       1005
#define IDC_BUTTONSEND                  1005
#define IDC_DEST_PORT                   1005
#define IDC_PROGRESS_BAR                1005
#define IDC_LIST_EXE                    1006
#define IDC_SENDMSG                     1006
#define IDC_STATUS                      1006
#define IDC_CHECK_CLOSESEND             1006
#define IDC_DEST_MASK                   1006
#define IDC_PROMPT                      1006
#define IDC_BTN_ADD                     1007
#define IDC_EDITLOG                     1007
#define IDC_CHECK_CLOSERECV             1007
#define IDC_PROTOCOL                    1007
#define IDC_SPIN1                       1007
#define IDC_EDIT_PROCESS_REFRESH        1007
#define IDC_BTN_DELETE                  1008
#define IDC_SEND                        1008
#define IDC_CHECK_TOPMOST               1008
#define IDC_EDIT_SHUTDOWN_DELAY         1008
#define IDC_EDIT_EXE                    1009
#define IDC_PROLIST                     1009
#define IDC_ACTION                      1009
#define IDC_EDIT_COMMANDLINE            1010
#define IDC_SYSMSG                      1010
#define IDC_COMBO_USERINTERFACE         1011
#define IDC_EDIT_PAUSESTART             1012
#define IDC_BOUDRATE                    1012
#define IDC_EDIT_PAUSE_END              1013
#define IDC_BTN_CREATE_SETTING_FILE     1014
#define IDC_EDIT_SERVICENAME            1015
#define IDC_EDIT_INTERGAP               1016
#define IDC_LIST_RECORD                 1022
#define IDC_EDIT_SEND_MSG               1023
#define IDC_BTN_SEND                    1024
#define IDC_BTN_CLEAR                   1025
#define IDC_LIST_ONLINE_USER            1026
#define IDC_LIST_UDP_TABLE              1027
#define IDC_LIST_TCP_TABLE              1028
#define IDC_STATIC_TYPE                 1030
#define IDC_BTN_FUNCTION                1031
#define IDC_IPADDRESS1                  1032
#define IDC_BTN_CHANGE_DEFAULT_GATEWAY  1033
#define IDC_EDIT_FIRST_INTERFACE_DESC   1034
#define IDC_STATIC_ADAPT_NAME           1035
#define IDC_STATIC_ADAPTER_INDEX        1036
#define IDC_STATIC_ADAPTER_NUM          1037
#define IDC_IPADDRESS2                  1038
#define IDC_BTN_GET_MAC                 1039
#define IDC_STATIC_MAC_ADDRESS          1040
#define IDC_BUTTON1                     1041
#define IDC_COMBO_INDEX                 1042
#define IDC_COMBO_IPADDR                1043
#define IDC_IPADDRESS                   1044
#define IDC_EDIT_LSP_DLL_PATH           1045
#define IDC_BTN_ENUM_PROTOCOLS          1046
#define IDC_BTN_LSP                     1046
#define IDC_BTN_REMOVE_LSP              1047
#define IDC_BTN_INSTALL_LSP             1048
#define IDC_EDIT_LSP_NAME               1049
#define IDC_LISTINFO                    1050
#define IDC_EDITINFO                    1051
#define IDC_BTN_MENU                    1052
#define IDC_LIST_RULES                  1054
#define IDC_LIST_USER                   1055
#define IDC_LIST_INFO                   1057
#define IDC_LIST_CONTENT                1058
#define IDC_EDIT_CONTENT                1061
#define IDC_COMBO_INTERFACE             1062
#define IDC_BTN_START_SNIFFER           1063
#define IDC_TREE_DATA                   1064
#define IDC_BTN_STOP                    1065
#define IDC_CMB_START_IP                1066
#define IDC_CMB_END_IP                  1067
#define IDC_CHECK_PING                  1068
#define IDC_STATIC_END_IP               1069
#define IDC_PIC_FROM                    1071
#define IDC_PIC_TO                      1072
#define IDC_EDIT_PING_TIMES             1073
#define IDC_BTN_START_PING              1075
#define IDC_BTN_TRACE                   1076
#define IDC_STATIC_INFO                 1077
#define IDC_LIST_HOST                   1079
#define IDC_LIST_MAC                    1080
#define IDC_BTN_WAKE                    1081
#define IDC_LIST_IP                     1082
#define IDC_EDIT_CMDLINE                1083
#define IDC_EDIT_DRIVER_PATH            1086
#define IDC_EDIT1                       1087
#define IDC_EDIT2                       1088
#define IDC_EDIT3                       1089
#define IDC_EDIT4                       1090
#define IDC_EDIT5                       1091
#define IDC_EDIT6                       1092
#define IDC_BTN_HIDE                    1093
#define IDC_BTN_SHOW                    1094
#define IDR_INSTALL_SERVICE             32771
#define ID_FILE_START                   32771
#define IDR_UNINSTALL_SERVICE           32772
#define ID_FILE_ADD_MACHINE             32772
#define ID_FILE_STOP                    32772
#define IDR_START_SERVICE               32773
#define ID_FILE_LOAD                    32773
#define IDR_STOP_SERVICE                32774
#define ID_RULES_ADD                    32774
#define IDR_RESTART_SERVICE             32775
#define IDR_REFRESH                     32776
#define ID_RULES_INSTALL                32776
#define IDM_IP_STATS                    32777
#define ID_RULES_UNINSTALL              32777
#define IDM_ICMP_STATS                  32778
#define IDM_TCP_STATS                   32779
#define IDM_UDP_STATS                   32780
#define ID_RULES_DELETE                 32780
#define IDM_REFRESH_ARP_TABLE           32781
#define ID_FILE_CONSERVE                32781
#define IDM_ADD_ARP_ENTRY               32782
#define IDM_DEL_ARP_ENTRY               32783
#define IDM_ENUM_PROTOCOL               32784
#define IDM_INSTALL_LSP                 32785
#define IDM_REMOVE_LSP                  32786
#define ID_SETTINGS_TIMERS              32786
#define IDM_HOOK_SOCKET                 32787
#define IDM_UNHOOK_SOCKET               32788
#define ID_SETTINGS_WINDOW_ALWAYSONTOP  32788
#define IDM_SAVE_RULES                  32789
#define IDM_IMPORT_RULES                32790
#define IDM_START_HOOK                  32791
#define IDM_STOP_HOOK                   32792
#define IDM_ADD_RULE                    32793
#define IDM_CLEAR_RULES                 32794
#define IDM_INSTALL_RULES               32795
#define IDM_DEL_RULE                    32796
#define ID_FILE_DELETE_MACHINE          32799
#define ID_FILE_REFRESHPROCESS          32800
#define ID_FILE_EXECUTE_PROCESS         32801
#define ID_FILE_SHUTDOWN_HALT           32802
#define ID_FILE_SHUTDOWN_REBOOT         32803
#define ID_FILESHUTDOWN_ABORTSHUTDOWN   32804
#define ID_FILE_KILL_PROCESS            32805
#define IDR_SEND_RAW_UDP_PACKET         32806
#define IDM_INSTALL_DRIVER              32807
#define IDM_UNINSTALL_DRIVER            32808
#define IDM_START_DRIVER                32809
#define IDM_STOP_DRIVER                 32810
#define IDM_HIDE_PROCESS                32811
#define IDM_OPEN_CONTROL_DEVICE         32812

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        170
#define _APS_NEXT_COMMAND_VALUE         32813
#define _APS_NEXT_CONTROL_VALUE         1095
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
