//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Tab.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_TABTYPE                     129
#define ID_VIEW_LARGEICONS              32771
#define ID_VIEW_DETAILS                 32773
#define ID_PARENT                       32775
#define ID_FOLDER_REMOVE                32782
#define ID_FOLDER_ADDTOCD               32791
#define ID_FOLDER_ADD                   32793

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1002
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
