//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TANGRAM.RC
//
#define IDD_TANGRAM_DIALOG              102
#define IDR_MAINFRAME                   128
#define IDR_POPUPMENU                   129
#define IDD_CONFIG_DIALOG               130
#define IDC_WORLD_GROUP                 1000
#define IDC_MODEL_GROUP                 1001
#define IDC_WORLD_LIST                  1002
#define IDC_MODEL_LOCAL_CHECK           1003
#define IDC_MODEL_ACTIVE_CHECK          1004

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE	131
#define _APS_NEXT_CONTROL_VALUE		1007
#define _APS_NEXT_SYMED_VALUE		101
#define _APS_NEXT_COMMAND_VALUE		32771
#endif
#endif
