//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CrashFinder.rc
//
//#define IDR_MANIFEST                    1
#define IDD_ABOUTBOX                    100
#define IDD_APPOPTIONS                  101
#define IDD_BINARYPROPERTIES            102
#define IDB_INFOITEM                    102
#define IDD_FINDCRASH                   103
#define IDD_IGNOREDDLG                  104
#define IDD_FIND_FORM                   104
#define IDB_BADITEM                     120
#define IDB_GOODITEM                    121
#define IDR_MAINFRAME                   128
#define IDR_CRASHFTYPE                  129
#define IDR_HINTDATA                    130
#define IDS_VERSIONREGKEY               130
#define IDS_ADDFILTER                   140
#define IDS_ADDTITLE                    141
#define IDS_DUPLICATEFILE               145
#define IDS_FILENOTFOUND                146
#define IDS_DUPLICATELOADADDR           147
#define IDS_DUPLICATELOADADDRFINAL      148
#define IDS_NOTPEIMAGE                  149
#define IDS_EXEALREADYINPROJECT         150
#define IDS_CONFIRMREMOVE               151
#define IDS_LOADADDRBADCONVERSION       152
#define IDS_CATASTROPHICFAILURE         153
#define IDS_SYMMODULENOTLOADED          154
#define IDS_FUNCNOTFOUND                155
#define IDS_LINENOTFOUND                156
#define IDS_DISPLACEMENTFMT             157
#define IDS_WEAKIMAGHLP                 158
#define IDS_NOMODULESLOADED             159
#define IDS_MODNOTFOUND                 160
#define IDS_LINEFMT                     161
#define IDS_IMAGEBASE                   162
#define IDS_IMAGEBASE64                 162
#define IDS_TIMESTAMP                   163
#define IDS_SYMBOLTYPE                  164
#define IDS_IMAGENAME                   165
#define IDS_LOADEDIMAGE                 166
#define IDS_ERR_NOTFOUND                167
#define IDS_ERR_LOADCONFLICT            168
#define IDS_ERR_NOSYMBOLS               169
#define IDS_ERR_NOPDBSYMBOLS            170
#define IDS_ERR_NOTAPEFILE              171
#define IDS_ERR_UNKNOWNERROR            172
#define IDS_IMAGEBASE65                 173
#define IDS_IMAGEBASE32                 173
#define IDS_ERR_WRONGMACHINE            174
#define IDC_SHOWFULLPATHS               1000
#define IDC_HYPERLINK                   1000
#define IDC_CONFIRMDELETIONS            1001
#define IDC_LOADADDREDIT                1002
#define IDC_HEXEDIT                     1003
#define IDC_FIND                        1004
#define IDC_ADDRESS                     1006
#define IDC_SHOWDISPLACEMENTS           1006
#define IDC_MODULE                      1007
#define IDC_FUNCTION                    1008
#define IDC_FNDISPLACEMENT              1009
#define IDC_SOURCEFILE                  1010
#define IDC_CLEAR                       1010
#define IDC_SOURCELINE                  1011
#define IDC_SRCDISPLACEMENT             1012
#define IDC_BIGICON                     1013
#define IDC_APPNAME                     1014
#define IDC_HINTS                       1015
#define IDC_DETAILS                     1016
#define IDC_ONELINE                     1017
#define IDC_IGNORELIST                  1018
#define IDC_INSERTTEXT                  1018
#define IDC_ADD                         1019
#define IDC_DELETE                      1020
#define ID_EDIT_FIND_CRASH              32771
#define ID_EDIT_ADD_IMAGE               32772
#define ID_EDIT_REMOVE_IMAGE            32773
#define ID_EDIT_IMAGE_PROPERTIES        32774
#define ID_VIEW_OPTIONS                 32775
#define ID_EDIT_IGNORED_IMAGE           32776
#define AFX_IDS_APP_TITLE               0xE000
#define AFX_IDS_IDLEMESSAGE             0xE001
#define ID_FILE_NEW                     0xE100
#define ID_FILE_OPEN                    0xE101
#define ID_FILE_CLOSE                   0xE102
#define ID_FILE_SAVE                    0xE103
#define ID_FILE_SAVE_AS                 0xE104
#define ID_FILE_MRU_FILE1               0xE110
#define ID_FILE_MRU_FILE2               0xE111
#define ID_FILE_MRU_FILE3               0xE112
#define ID_FILE_MRU_FILE4               0xE113
#define ID_FILE_MRU_FILE5               0xE114
#define ID_FILE_MRU_FILE6               0xE115
#define ID_FILE_MRU_FILE7               0xE116
#define ID_FILE_MRU_FILE8               0xE117
#define ID_FILE_MRU_FILE9               0xE118
#define ID_FILE_MRU_FILE10              0xE119
#define ID_FILE_MRU_FILE11              0xE11A
#define ID_FILE_MRU_FILE12              0xE11B
#define ID_FILE_MRU_FILE13              0xE11C
#define ID_FILE_MRU_FILE14              0xE11D
#define ID_FILE_MRU_FILE15              0xE11E
#define ID_FILE_MRU_FILE16              0xE11F
#define ID_EDIT_COPY                    0xE122
#define ID_WINDOW_ARRANGE               0xE131
#define ID_WINDOW_CASCADE               0xE132
#define ID_WINDOW_TILE_HORZ             0xE133
#define ID_WINDOW_TILE_VERT             0xE134
#define ID_APP_ABOUT                    0xE140
#define ID_APP_EXIT                     0xE141
#define ID_NEXT_PANE                    0xE150
#define ID_PREV_PANE                    0xE151
#define ID_INDICATOR_EXT                0xE700
#define ID_INDICATOR_CAPS               0xE701
#define ID_INDICATOR_NUM                0xE702
#define ID_INDICATOR_SCRL               0xE703
#define ID_INDICATOR_OVR                0xE704
#define ID_INDICATOR_REC                0xE705
#define ID_VIEW_TOOLBAR                 0xE800
#define ID_VIEW_STATUS_BAR              0xE801

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        105
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1011
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
