//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by PukamSoftRes.rc
//
#define IDB_MB_YES_HOVER_BUTTON         101
#define IDB_MB_CANCEL_HIT_BUTTON        102
#define IDB_MB_CANCEL_HOVER_BUTTON      103
#define IDB_MB_CONFIRMATION_ICON        104
#define IDB_MB_ERROR_ICON               105
#define IDB_MB_INFORMATION_ICON         106
#define IDB_MB_NO_BUTTON                107
#define IDB_MB_NO_HIT_BUTTON            108
#define IDB_MB_NO_HOVER_BUTTON          109
#define IDB_MB_OK_BUTTON                110
#define IDB_MB_OK_HIT_BUTTON            111
#define IDB_MB_OK_HOVER_BUTTON          112
#define IDB_MB_TOP_BAND                 113
#define IDB_MB_WARNING_ICON             114
#define IDB_MB_YES_BUTTON               115
#define IDB_MB_YES_HIT_BUTTON           116
#define IDB_MB_CANCEL_BUTTON            117
#define IDB_MM_CI_NORMAL                118
#define IDB_MM_CI_HOVER                 119
#define IDB_MM_CI_HIT                   120
#define IDB_MM_IT_NORMAL                121
#define IDB_MM_IT_HOVER                 122
#define IDB_MM_IT_HIT                   123
#define IDB_MM_OT_NORMAL                124
#define IDB_MM_OT_HOVER                 125
#define IDB_MM_OT_HIT                   126
#define IDB_MM_BI_NORMAL                127
#define IDB_MM_BI_HOVER                 128
#define IDB_MM_BI_HIT                   129
#define IDB_MM_RE_NORMAL                130
#define IDB_MM_RE_HOVER                 131
#define IDB_MM_RE_HIT                   132
#define IDB_MM_BACKGROUND               133
#define IDB_CI_CUSTOMERID_STATIC        134
#define IDB_CI_COMPANYNAME_STATIC       135
#define IDB_CI_CONTACTPERSON_STATIC     136
#define IDB_CI_ADDRESS1_STATIC          137
#define IDB_CI_ADDRESS2_STATIC          138
#define IDB_CI_PHONER_STATIC            139
#define IDB_CI_PHONEO_STATIC            140
#define IDB_CI_CELL_STATIC              141
#define IDB_CI_FAX_STATIC               142
#define IDB_CI_EMAIL_STATIC             143
#define IDB_IT_CUSTOMERID_STATIC        144
#define IDB_IT_SERIALNUMBER_STATIC      145
#define IDB_IT_DATE_STATIC              146
#define IDB_IT_CATEGORY_STATIC          147
#define IDB_IT_SIZE_STATIC              148
#define IDB_IT_WEIGHT_STATIC            149
#define IDB_IT_QUANTITY_STATIC          150
#define IDB_IT_STORAGELOCATION_STATIC   151
#define IDB_DROPDOWN_NORMAL             152
#define IDB_DROPDOWN_HIT                153
#define IDB_BITMAP_SCROLLBAR_UP         154
#define IDB_BITMAP_SCROLLBAR_BACK       155
#define IDB_BITMAP_SCROLLBAR_DOWN       156
#define IDB_BITMAP_SCROLLBAR_BUTTON     157
#define IDB_OT_CUSTOMERID_STATIC        158
#define IDB_OT_SERIALNUMBER_STATIC      159
#define IDB_OT_DATE_STATIC              160
#define IDB_OT_GATEPASSNUMBER_STATIC    161
#define IDB_OT_QUANTITY_STATIC          162
#define IDB_BI_CUSTOMERID_STATIC        163
#define IDB_BI_SERIALNUMBER_STATIC      164
#define IDB_BI_RATE_STATIC              165
#define IDB_BI_FREQUENCY_STATIC         166
#define IDB_BI_DATE_STATIC              167
#define IDB_BI_PAYMENTMODE_STATIC       168
#define IDB_BI_BILLNUMBER_STATIC        169
#define IDB_SAVEDETAILS                 171
#define IDB_SAVEDETAILS_HOVER           172
#define IDB_SAVEDETAILS_HIT             173
#define IDB_MM_TOPBAND                  174
#define IDB_MM_BOTTOMBAND               175
#define IDB_CI_TOPBAND                  176
#define IDB_IT_TOPBAND                  177
#define IDB_OT_TOPBAND                  178
#define IDB_BI_TOPBAND                  179
#define IDB_TB_STRIP                    180
#define IDB_TB_TITLEMAIN                181
#define IDB_TB_PIPE                     182
#define IDB_TB_SUBTITLECI               183
#define IDB_TB_SUBTITLEIT               184
#define IDB_TB_SUBTITLEOT               185
#define IDB_TB_SUBTITLEBI               186
#define IDB_LN_STRIP                    187
#define IDB_COMMONSTRIP                 188
#define IDB_LN_CI_NORMAL                189
#define IDB_LN_IT_NORMAL                190
#define IDB_LN_OT_NORMAL                191
#define IDB_LN_BI_NORMAL                192
#define IDB_LN_RE_NORMAL                193
#define IDB_TB_CLOSE                    194
#define IDB_LN_CI_HOVER                 195
#define IDB_LN_IT_HOVER                 196
#define IDB_LN_OT_HOVER                 197
#define IDB_LN_BI_HOVER                 198
#define IDB_TB_SUBTITLERE               199
#define IDB_LN_RE_HOVER                 200
#define IDB_UNCHECK                     201
#define IDB_CHECK                       202
#define IDB_RE_IT_NORMAL                203
#define IDB_RE_OT_NORMAL                204
#define IDB_RE_CI_NORMAL                205
#define IDB_LN_OT_BG                    206
#define IDB_LN_RE_BG                    207
#define IDB_LN_BI_BG                    208
#define IDB_LN_IT_BG                    209
#define IDB_LN_CI_BG                    210
#define IDB_MM_STRIP                    211
#define IDB_RE_CI_HOVER                 212
#define IDB_RE_IT_HOVER                 213
#define IDB_RE_OT_HOVER                 214
#define IDB_TB_HOME                     215
#define IDB_DELETE_NORMAL               216
#define IDB_DELETE_HIT                  217
#define IDB_MODIFY_NORMAL               218
#define IDB_MODIFY_HIT                  219

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        220
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
