#ifndef SKIN_CONTROLS_H_
#define SKIN_CONTROLS_H_
#pragma once

#include "SkinControlsDefine.h"

#include "SystemHelpers.h"
#include "DrawHelpers.h"
#include "BitmapPng.h"
#include "SkinImage.h"
#include "SkinHelper.h"

#include "SkinSB.h"
#include "SkinScrollBar.h"
#include "SkinButton.h"
#include "SkinCheckBox.h"
#include "SkinRadioBox.h"
#include "SkinCheckButton.h"
#include "SkinRadioButton.h"
#include "SkinEdit.h"
#include "SkinComboBox.h"
#include "SkinHyperLink.h"
#include "SkinStatic.h"
#include "SkinTabCtrl.h"
#include "SkinSplitter.h"
#include "SkinSliderCtrl.h"
#include "SkinProgressCtrl.h"
#include "SkinListCtrl.h"
#include "SkinTreeCtrl.h"
#include "SkinMenu.h"
#include "SkinRichEdit.h"
#include "SkinWindow.h"
#include "SkinDialog.h"
#include "SkinLayeredWnd.h"
#include "SkinMsgBox.h"
#include "GifImage.h"
#include "GifAnimation.h"

#include "DUIManager.h"
#include "DUIControl.h"
#include "DUILabel.h"
#include "DUIButton.h"
#include "DUICheckBox.h"
#include "DUIRadioBox.h"
#include "DUIProgress.h"
#include "DUISlider.h"
#include "DUIGroupBox.h"
#include "DUITabButton.h"
#include "DUIImageControl.h"
#include "DUIDlgBuilder.h"
#include "DuiWnd.h"
#include "DuiDialog.h"

#endif // SKIN_CONTROLS_H_