//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by INTSIM.RC
//
#define MAINDLG                         101
#define IDB_INTERRUPT                   1000
#define IDB_EXIT                        1001

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1002
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
