//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Dialog2.rc
//
#define IDD_WNDSIZE                     101
#define IDD_ABOUTBOX                    102
#define IDD_DIALOG1                     103
#define IDD_DLGBAR                      103
#define IDD_DIALOG2                     104
#define IDR_MAINFRAME                   128
#define IDC_RADIO_320                   1000
#define IDC_COMBO1                      1000
#define IDC_RADIO_640                   1001
#define IDC_RADIO_800                   1002
#define IDC_EDIT1                       1002
#define IDC_RADIO_1024                  1003
#define IDC_RADIO_DESKTOP               1004
#define IDC_EDIT_WIDTH                  1006
#define IDC_EDIT_HEIGHT                 1007
#define IDC_RADIO_CUSTOM                1008
#define IDC_STATIC_WIDTH                1009
#define IDC_STATIC_HEIGHT               1010
#define ID_FILE_EXIT                    32775
#define ID_HELP_ABOUT                   40008
#define ID_DIALOG_WNDSIZE               40009
#define ID_INDICATOR_CAPS               0xE701
#define ID_INDICATOR_NUM                0xE702
#define ID_INDICATOR_SCRL               0xE703

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        105
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
