//////////////////////////////////////////////////////////////////////////////////////
//
// WorldCat.h - Definition of the TangramWorldCategory component category.
//
//////////////////////////////////////////////////////////////////////////////////////
//
// A component which supports the following interfaces can be a member of the 
// TangramWorldCategory component category:
//
//		ITangramWorld
//		ITangramCanvas
//

// {b53313d0-20c4-11d0-9c6c-00a0c90a632c}
DEFINE_GUID(CATID_TangramWorldCategory, 
0xb53313d0, 0x20c4, 0x11d0, 0x9c, 0x6c, 0x0, 0xa0, 0xc9, 0xa, 0x63, 0x2c);
