//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by DllTest1.rc
//
#define IDR_MENU1                       101
#define IDR_MAINFRAME                   101
#define IDD_ABOUTBOX                    102
#define ID_APPEXIT                      40001
#define ID_FILE_EXIT                    40001
#define ID_HELP_ABOUT                   40002
#define ID_FILE_CALLSDKDLL              40003
#define ID_FILE_CALLREGULARDLL          40004
#define ID_FILE_CALLMFCDLL              40004
#define ID_FILE_CALLEXTENSIONDLL        40005

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        103
#define _APS_NEXT_COMMAND_VALUE         40007
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
