//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by TEST.RC
//
#define IDR_MAINFRAME                   2
#define IDR_TESTTYPE                    3
#define IDD_ABOUTBOX                    100
#define IDC_ZOOMCURSOR                  101
#define ID_VIEW_ZOOMIN                  32769
#define ID_VIEW_ZOOMOUT                 32770
#define ID_VIEW_ZOOMFULL                32771

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        108
#define _APS_NEXT_COMMAND_VALUE         32775
#define _APS_NEXT_CONTROL_VALUE         104
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
