; CLW file contains information for the MFC ClassWizard

[General Info]
Version=1
LastClass=CZoomView
LastTemplate=CDialog
NewFileInclude1=#include "stdafx.h"
NewFileInclude2=#include "test.h"
VbxHeaderFile=test.h
VbxImplementationFile=test.cpp

ClassCount=6
Class1=CMainFrame
Class2=CTestApp
Class3=CAboutDlg
Class4=CTestDoc
Class5=CTestView
Class6=CZoomView

ResourceCount=3
Resource1=IDR_TESTTYPE
Resource2=IDR_MAINFRAME
Resource3=IDD_ABOUTBOX

[CLS:CMainFrame]
Type=0
HeaderFile=mainfrm.h
ImplementationFile=mainfrm.cpp

[CLS:CTestApp]
Type=0
HeaderFile=test.h
ImplementationFile=test.cpp

[CLS:CAboutDlg]
Type=0
HeaderFile=test.cpp
ImplementationFile=test.cpp

[CLS:CTestDoc]
Type=0
HeaderFile=testdoc.h
ImplementationFile=testdoc.cpp

[CLS:CTestView]
Type=0
HeaderFile=testview.h
ImplementationFile=testview.cpp

[CLS:CZoomView]
Type=0
HeaderFile=zoomview.h
ImplementationFile=zoomview.cpp
LastObject=CZoomView

[MNU:IDR_MAINFRAME]
Type=1
Command1=ID_FILE_NEW
Command2=ID_FILE_PRINT_SETUP
Command3=ID_FILE_MRU_FILE1
Command4=ID_APP_EXIT
Command5=ID_VIEW_TOOLBAR
Command6=ID_VIEW_STATUS_BAR
Command7=ID_APP_ABOUT
CommandCount=7
Class=?

[MNU:IDR_TESTTYPE]
Type=1
Command1=ID_FILE_NEW
Command2=ID_FILE_CLOSE
Command3=ID_FILE_PRINT
Command4=ID_FILE_PRINT_PREVIEW
Command5=ID_FILE_PRINT_SETUP
Command6=ID_FILE_MRU_FILE1
Command7=ID_APP_EXIT
Command8=ID_VIEW_ZOOMIN
Command9=ID_VIEW_ZOOMOUT
Command10=ID_VIEW_ZOOMFULL
Command11=ID_VIEW_TOOLBAR
Command12=ID_VIEW_STATUS_BAR
Command13=ID_WINDOW_NEW
Command14=ID_WINDOW_CASCADE
Command15=ID_WINDOW_TILE_HORZ
Command16=ID_WINDOW_ARRANGE
Command17=ID_APP_ABOUT
CommandCount=17
Class=?

[ACL:IDR_MAINFRAME]
Type=1
Command1=ID_NEXT_PANE
Command2=ID_PREV_PANE
Command3=ID_VIEW_ZOOMOUT
Command4=ID_VIEW_ZOOMIN
Command5=ID_VIEW_ZOOMFULL
CommandCount=5
Class=?

[DLG:IDD_ABOUTBOX]
Type=1
ControlCount=4
Control1=IDC_STATIC,static,1342177283
Control2=IDC_STATIC,static,1342308352
Control3=IDC_STATIC,static,1342308352
Control4=IDOK,button,1342373889
Class=CAboutDlg

